#!/bin/sh
#
# Copyright (c) 2013 Nate Diller.
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of the "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nate Diller - Initial contribution.
#
# Contributors:
# 
# Description:
#
#


#PYCMD="/cygdrive/c/Python27/python.exe"
PYCMD="python"

$PYCMD joinfs_helper.py $1 $2 | while read -r line
do
    echo subscriber.py $line $3
    $PYCMD subscriber.py $line $3 &
done

